### ISSUE TITLE
Make second step of sharing proof intuitive for users

### ISSUE THREAD

**Issue by Ma-Tza** [guardianproject/proofmode#12] opened 2017-02-28 18:16 UTC
The second step of sharing, after you tap ShareProof - how can we make the user experience of that step more intuitive - Eg, ShareProof should not appear as an option at that second step. Also can we limit the number of apps that appear at the second step? Can we make that window look a bit different so users don't get confused with previous step?

**Comment by n8fr8** [comment] 2017-03-01 15:49
This is a duplicate of #11 - will move your comment there

**Closed by n8fr8** 2017-03-01 15:49 UTC
